imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  null
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # Custom mapping types are registered in ShopBundle::boot() method

        types:
            customer_cart_items:
                class: Dumplie\Customer\Infrastructure\Doctrine\ORM\Type\Domain\CartItemsType
                commented: true
            customer_order_items:
                class: Dumplie\Customer\Infrastructure\Doctrine\ORM\Type\Domain\OrderItemsType
                commented: true

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            DumplieShareKernel:
                type: xml
                dir: '%dumplie.root_dir%/SharedKernel/Infrastructure/Doctrine/ORM/Resources/Mapping/Domain'
                is_bundle: false
                prefix: Dumplie\SharedKernel\Domain
                alias: DumplieSharedKernel
            InventoryCustomer:
                type: xml
                dir: '%dumplie.root_dir%/Inventory/Infrastructure/Doctrine/ORM/Resources/Mapping/Domain'
                is_bundle: false
                prefix: Dumplie\Inventory\Domain
                alias: DumplieInventory
            Customer:
                type: xml
                dir: '%dumplie.root_dir%/Customer/Infrastructure/Doctrine/ORM/Resources/Mapping/Domain'
                is_bundle: false
                prefix: Dumplie\Customer\Domain
                alias: Customer

metadata:
  storage:
    doctrine:
      connection: "database_connection"

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }
